apiVersion: batch/v1
kind: CronJob
metadata:
  name: harvester-auto-clean
  namespace: default
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity: {}
          containers:
          - args:
            - default
            - harvester-public
            command:
            - /tmp/harvester-clean.sh
           env:
            - name: KUBECONFIG
              value: /tmp/harv-102.config
            image: bitnami/kubectl:1.21
            imagePullPolicy: IfNotPresent
            name: container-0
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /tmp/harvester-clean.sh
              name: vol0
              subPath: harvester-clean.sh
            - mountPath: /tmp/harv-102.config
              name: vol1
              subPath: harv-102.config
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 493
              name: harvester-clean
            name: vol0
         - name: vol1
            secret:
              defaultMode: 420
              secretName: kubeconfig
  schedule: 0 15 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
